---
alg: lstm_ed
base_dir: log/lstm_ed/data_load_area
log_level: INFO
gpu: 0
data:
  batch_size: 200
  dataset: data/data_load_area.npz
  eval_batch_size: 1
  test_batch_size: 1
  test_size: 0.2
  valid_size: 0.2
model:
  model_type: ed
  seq_len: 24
  horizon: 1
  input_dim: 1
  verified_percentage: 1
  l1_decay: 0
  nodes: 29
  output_dim: 1
  rnn_units: 100
  rnn_layers: 1
train:
  dropout: 0.5
  epochs: 300
  optimizer: adam
  patience: 20
  continue_train: False
test:
  run_times: 1
